name: 'chore: update activity stream'

on:
  schedule:
    # Run at 00:00 EST
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update this repo's README with recent activity

    steps:
      - uses: actions/checkout@v2
      - uses: hyduez/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          EVENT_CREATE: true
          EVENT_DELETE: true
          EVENT_ISSUE_COMMENT: true
          EVENT_COMMIT_COMMENT: true
          EVENT_PUSH: true
          EVENT_WATCH: true
          IGNORE_REPOS: 'hyduez/hyduez hyduez/github-activity-readme'
          COMMIT_MSG: 'chore: update activity stream'
          
