name: Waka Readme

on:
  schedule:
    # Runs at 12am EST
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.WAKA_GIT }}
          SHOW_PROFILE_VIEWS: 'False'
          SHOW_UPDATED_DATE: 'False'
          SHOW_COMMITS: 'False'
          SHOW_TOTAL_CODE_TIME: 'False'
          SHOW_SHORT_INFO: 'False'
          COMMIT_BY_ME: 'False'
          SYMBOL_VERSION: 2
          SHOW_DAYS_OF_WEEK: 'False'
          LOCALE: 'en'
